// generated by cdktf get
Object.defineProperty(exports, 'application', { get: function () { return require('./application'); } });
Object.defineProperty(exports, 'auth', { get: function () { return require('./auth'); } });
Object.defineProperty(exports, 'authIdpConfig', { get: function () { return require('./auth-idp-config'); } });
Object.defineProperty(exports, 'authMachineUser', { get: function () { return require('./auth-machine-user'); } });
Object.defineProperty(exports, 'authOauth2Client', { get: function () { return require('./auth-oauth2-client'); } });
Object.defineProperty(exports, 'authScimConfig', { get: function () { return require('./auth-scim-config'); } });
Object.defineProperty(exports, 'authScimResource', { get: function () { return require('./auth-scim-resource'); } });
Object.defineProperty(exports, 'authUserProfileConfig', { get: function () { return require('./auth-user-profile-config'); } });
Object.defineProperty(exports, 'executor', { get: function () { return require('./executor'); } });
Object.defineProperty(exports, 'organizationAccess', { get: function () { return require('./organization-access'); } });
Object.defineProperty(exports, 'organizationFolder', { get: function () { return require('./organization-folder'); } });
Object.defineProperty(exports, 'organizationFolderAccess', { get: function () { return require('./organization-folder-access'); } });
Object.defineProperty(exports, 'organizationTeam', { get: function () { return require('./organization-team'); } });
Object.defineProperty(exports, 'organizationTeamMember', { get: function () { return require('./organization-team-member'); } });
Object.defineProperty(exports, 'pipeline', { get: function () { return require('./pipeline'); } });
Object.defineProperty(exports, 'pipelineResolver', { get: function () { return require('./pipeline-resolver'); } });
Object.defineProperty(exports, 'secretmanagerSecret', { get: function () { return require('./secretmanager-secret'); } });
Object.defineProperty(exports, 'secretmanagerVault', { get: function () { return require('./secretmanager-vault'); } });
Object.defineProperty(exports, 'stateflow', { get: function () { return require('./stateflow'); } });
Object.defineProperty(exports, 'tailordb', { get: function () { return require('./tailordb'); } });
Object.defineProperty(exports, 'tailordbType', { get: function () { return require('./tailordb-type'); } });
Object.defineProperty(exports, 'workspace', { get: function () { return require('./workspace'); } });
Object.defineProperty(exports, 'dataTailorOrganization', { get: function () { return require('./data-tailor-organization'); } });
Object.defineProperty(exports, 'dataTailorWorkspace', { get: function () { return require('./data-tailor-workspace'); } });
Object.defineProperty(exports, 'dataTailorWorkspaces', { get: function () { return require('./data-tailor-workspaces'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

